// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5nUhIGyNsmmkml4dJlQKqXMzAoM3IX3s',
    appId: '1:57926949450:web:d2191b439a9d261d3164b3',
    messagingSenderId: '57926949450',
    projectId: 'mykuya-35bb4',
    authDomain: 'mykuya-35bb4.firebaseapp.com',
    storageBucket: 'mykuya-35bb4.firebasestorage.app',
    measurementId: 'G-N9KGJLS07P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLNwUFVhGzAA9R9lCe779tyqRCyPfXy6M',
    appId: '1:57926949450:android:b74040357860b5023164b3',
    messagingSenderId: '57926949450',
    projectId: 'mykuya-35bb4',
    storageBucket: 'mykuya-35bb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZYJMbnmVd-raw1ZZFzs8Dx2BPa6kk7f0',
    appId: '1:57926949450:ios:14c0fec2789a9bab3164b3',
    messagingSenderId: '57926949450',
    projectId: 'mykuya-35bb4',
    storageBucket: 'mykuya-35bb4.firebasestorage.app',
    iosBundleId: 'com.example.mykuya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZYJMbnmVd-raw1ZZFzs8Dx2BPa6kk7f0',
    appId: '1:57926949450:ios:14c0fec2789a9bab3164b3',
    messagingSenderId: '57926949450',
    projectId: 'mykuya-35bb4',
    storageBucket: 'mykuya-35bb4.firebasestorage.app',
    iosBundleId: 'com.example.mykuya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5nUhIGyNsmmkml4dJlQKqXMzAoM3IX3s',
    appId: '1:57926949450:web:ce22731b5690133f3164b3',
    messagingSenderId: '57926949450',
    projectId: 'mykuya-35bb4',
    authDomain: 'mykuya-35bb4.firebaseapp.com',
    storageBucket: 'mykuya-35bb4.firebasestorage.app',
    measurementId: 'G-JT4ZCW8X8B',
  );
}
